from .auth import router
from .employee import router
from .upload_employees import router
from .category import router
from .product import router
from .pricelist import router
from .pricelist_line import router
from .program import router
from .program_item import router
