"""fix program_type constraint

Revision ID: 62595d369a42
Revises: e0f7a1dbb5ab
Create Date: 2025-02-14 17:55:22.659657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62595d369a42'
down_revision: Union[str, None] = 'e0f7a1dbb5ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted by me ###
    op.drop_constraint('programs_check', 'programs', type_='check')
    op.create_check_constraint(
        "program_type_constraints", 
        "programs", 
        "(program_type = 'Coupon' AND discount IS NOT NULL AND product_to_buy_id IS NULL AND product_to_get_id IS NULL) "
        "OR (program_type = 'BuyXgetY' AND discount IS NULL AND product_to_buy_id IS NOT NULL AND product_to_get_id IS NOT NULL)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted by me ###
    op.drop_constraint("program_type_constraints", "programs", type_="check")
    op.create_check_constraint(
        "programs_check", 
        "programs", 
        "(discount IS NULL AND product_to_buy_id IS NOT NULL AND product_to_get_id IS NOT NULL) OR (discount IS NOT NULL AND product_to_buy_id IS NULL AND product_to_get_id IS NULL)"
    )
    # ### end Alembic commands ###
