"""make product_to_by_id and product_to_get_id nullable

Revision ID: e0f7a1dbb5ab
Revises: 772918d9cdac
Create Date: 2025-02-14 16:35:18.285312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f7a1dbb5ab'
down_revision: Union[str, None] = '772918d9cdac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted by me ###
    op.alter_column('programs', 'product_to_buy_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('programs', 'product_to_get_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted by me  ###
    op.alter_column('programs', 'product_to_get_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('programs', 'product_to_buy_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
