"""add public_id in prodcuts and categories table

Revision ID: f77c94346873
Revises: 62595d369a42
Create Date: 2025-02-15 14:47:08.477224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f77c94346873'
down_revision: Union[str, None] = '62595d369a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted by me ###
    op.add_column('categories', sa.Column('public_id', sa.String(), nullable=True))
    op.add_column('products', sa.Column('public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted by me ###
    op.drop_column('products', 'public_id')
    op.drop_column('categories', 'public_id')
    # ### end Alembic commands ###
